### ISSUE TITLE
Missing settings.py

### ISSUE THREAD

**Issue by xiconet** [hybridpicker/fretboard-position-finder#27]
First of all, thank you very much for sharing your work. I'd very much  like to use it locally but since I'm very new to Django, a `settings.py` file would be of much help. Could you please provide this file? Thanks in advance.

**Comment by hybridpicker** [comment]
Thank you for your feedback and request! I appreciate your interest in my project.

I've updated the app and added a standard settings.py file. You can find this file in the main directory of the project. Please refer to the comments within the file if there are specific configuration instructions.

If you have any further questions or encounter any issues, please don't hesitate to reach out again. Best of luck using the app!
