### ISSUE TITLE
Missing   "Minor Blues"   and   "Minor Pentatonic Scale"  in  Scales Selection

### ISSUE THREAD

**Issue by lizyyy** [hybridpicker/fretboard-position-finder#35]
Missing   "Minor Blues"   and   "Minor Pentatonic Scale"  in  Scales Selection

**Comment by hybridpicker** [comment]
Minor Blues is the Blues Scale, Minor Pentatonic Scale is now available.

**Comment by hybridpicker** [comment]
Also uploaded at guitar-positions.org. Have fun
