### ISSUE TITLE
Scales doesnt' appear to be working properly

### ISSUE THREAD

**Issue by timparkin** [hybridpicker/fretboard-position-finder#41]
I checked out the repository and got it working pretty quickly once the secret code and a database was added to settings. I made a note of this at the end of this issue. 

However, when I tried the chords section, it didn't seem to be working so I tried to figure out what I got wrong but then checked what it should look like and it didn't seem to be working on your website either.  

There appears to be an uncaught reference in chords.js 

I found it was missing the closeAllSelect function in fretboardbase_chords.html which is in the other HTML templates and so copied it over and it seems to be working now. 

Do you have any suggestions on how to get arpeggios listing tensions (and notes potentially?). Happy to hack around but a pointer would be really useful! 

Great work on this - a really cool resource!

Tim

[patch.txt](https://github.com/hybridpicker/fretboard-position-finder/files/14113473/patch.txt)

In settings.py
`
+SECRET_KEY = '<insert code>'
+
+os.path.join(BASE_DIR, 'templates')
+
+
+DATABASES = {
+    'default': {
+        'ENGINE': 'django.db.backends.sqlite3',
+        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
+    },
+}
`

**Comment by hybridpicker** [comment]
Do you got the same issue on the website? https://guitar-positions.org/
