### ISSUE TITLE
note_range and position_select don't seem to be working

### ISSUE THREAD

**Issue by timparkin** [hybridpicker/fretboard-position-finder#42]
![2024-01-31_15-39-39](https://github.com/hybridpicker/fretboard-position-finder/assets/8583/a8c97811-13d5-4083-9f44-eec37d99628e)
The buttons don't have the 'sesi' class to style them and they don't seem to be functional. 

If I remove display:none from the select elements, I can pick them and they display almost correctly so something is coded in there, but I get ghost notes appearing as I switch.. it's so close I'm frustrated at being able to find what it isn't doing :-)

**Comment by hybridpicker** [comment]
You can play with the whole masterbranch here ;-) https://guitar-positions.org/
It seems to work for me.

**Comment by timparkin** [comment]
Yes it does it on the website too... in multiple browsers. Switch to chords and it only shows "show tensions" as a proper button, then 'e-g' and 'Basic Position' just as text (and not clickable)

**Comment by hybridpicker** [comment]
New Version is now online should work. Thx for the feedback!
