### ISSUE TITLE
dominant 7 arpeggio's don't have positions

### ISSUE THREAD

**Issue by timparkin** [hybridpicker/fretboard-position-finder#43]
Sorry to bombard you with issues! I'm trying to reuse existing code instead of writing my own and yours is as comprehensive as I've seen but I'm struggling to decipher some areas. I'd like to have positions for the dominant 7th arpeggio's but I can't find out where to define these. I have a feeling they're in the database dump (json). All the other arpeggios seem to have positions.

**Comment by hybridpicker** [comment]
You were right, positions for dominant 7 are now available.
